### ISSUE TITLE
Bobo - Final Project Memo WP-1

### ISSUE THREAD

**Issue by c138b460** [slu-soc5650/final-project#3]
For my final project, I'm hoping to answer the following question: "Where do smaller and larger (in terms of asset size) banks have branches in the St. Louis Metropolitan area?" My goal is to see if there is a relationship between the size of a bank and their distribution of branches within the St. Louis Area. For example, this effort should reveal if the majority of "larger banks" opening/maintaining branches in the Central and Western portions of the MSA, while smaller institutions are locating in less populated and/or more racially diverse areas in the Northern, Southern, and Eastern portions of the MSA. This question fits neatly into ongoing research and national conversations about the accessibility of branches within communities across the country.

Regarding a data set, I'd like to [FDIC's Summary of Deposit data](https://www7.fdic.gov/sod/dynaDownload.asp?barItem=6) which meets the criteria outlined for the project. The data is collected periodically from all financial institutions and is available to the public. From the dataset, I hope to use the following columns:

"ADDRESSBR" for Address
"ASSET" for Asset size of the institution owning the branch
"CITY2BR" for City of the branch
"CNTYNAMB" for the County of the branch
"MSABR" to determine if the branch is in the MSA
"NAMEBR" for the name of the branch
"STALPBR" for the state of the branch
"UNINUMBR" for a unique identifier of each branch
"ZIPBR" for the zipcode associated with each branch
"SIMS_Latitutude" for the latitude of the branch
"SIMS_Longitutde" for the longitude of the branch
My hope is that these columns allow me to identify branches throughout the metropolitan area and assign an income designation to each.

**Comment by chris-prener** [comment]
Sounds good! I think this might involve a bit of extra work to get your data set together, just want to flag that you're biting off a bit more than I expect. As long as you are OK with that, I'm good with the topic!

**Comment by c138b460** [comment]
That's okay with me, thanks!
