### ISSUE TITLE
Memo

### ISSUE THREAD

**Issue by Carl7138** [slu-soc5650/final-project#5]
The final research question for Carl Cunningham

1. Does "Hot-Spot Policing" have an effect on violent crime in the city of st. Louis?
2. I will use violent crime data from the crime data list
3. I would like to map utilizing the following categories:
   a. Homicide
   b. Rape
   c. Robbery
   d. Aggravated Assault

**Comment by chris-prener** [comment]
Hi @Carl7138 - interesting. Do you have access to data on where hot spot policing has occurred in STL?

**Comment by Carl7138** [comment]
Hi @chris-prener, I believe I do. But i was hoping to make sure i got the assignment submitted on time, and thought there may be a chance to adjust once I have a better understanding of what's going on here. I'm still struggling with understanding with getting a clear understanding of what we are doing and where we are.

**Comment by chris-prener** [comment]
@Carl7138 - can you move this over to your Final Project repo and tag me there? Just realized you're in the main final project instructions repository!
